Lab_3/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import trash.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(trash.urls, namespace='trash')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trash/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'manager/$', views.FileManager.as_view(), name="filemanager"),
    url(r'trash/$', views.TrashList.as_view(), name='trash'),
    url(r'trash/detail/$', views.TrashView.as_view(), name='detail_trash'),
    url(r'task/$', views.TaskView.as_view(), name='task'),
    url(r'task/create/$', views.TaskCreate.as_view(), name='task_create')
]

trash/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils import timezone

from ssrc.trash import Trash as MyTrash
from functools import partial
import pathos.multiprocessing as multiprocessing
import json


class Trash(models.Model):

    trash_dir = models.CharField(max_length=50)
    info_dir = models.CharField(max_length=50)
    name_trash = models.CharField(max_length=50)

    def __str__(self):
        return self.name_trash

    def clean(self):
        t = MyTrash()
        t.clear_all_trash(self.trash_dir, self.info_dir)


class Task(models.Model):
    ACTION_CHOICE = (
        ('delete', 'delete'),
        ('restore', 'restore'),
    )
    STATUS = (
        ('complete', 'complete'),
        ('inprogress', 'inprogress'),
        ('error', 'error'),
    )
    date = models.DateTimeField(default=timezone.now)
    files = models.CharField(max_length=500)
    action = models.CharField(max_length=50, choices=ACTION_CHOICE)
    status = models.CharField(max_length=50, choices=STATUS)
    policy = models.CharField(max_length=50)
    trash = models.ForeignKey(Trash)
    regex = models.CharField(max_length=50, blank=True, null=True)

    def get_files(self):
        return json.loads(self.files)

    def execute(self):
        try:
            pool_size = multiprocessing.cpu_count() * 2
            pool = multiprocessing.Pool(processes=pool_size)

            files = self.get_files()

            if self.action == 'delete':
                t = MyTrash(policy_delete=self.policy)
                if self.regex:
                    delete_func = partial(t.regex_delete,
                                          regex=self.regex,
                                          path_directory_of_trash=self.trash.trash_dir,
                                          path_info=self.trash.info_dir,
                                          max_size=500000)
                else:
                    delete_func = partial(t.delete,
                                          path_directory_of_trash=self.trash.trash_dir,
                                          path_info=self.trash.info_dir,
                                          max_size=500000)

                pool.map(delete_func, files)
            if self.action == 'restore':
                t = MyTrash(policy_restore=self.policy)
                restore_func = partial(t.restore,
                                       path_directory_of_trash=self.trash.trash_dir,
                                       path_info=self.trash.info_dir,
                                       max_size=500000)

                pool.map(restore_func, files)
            pool.close()
            pool.join()
            self.status = 'complete'
            self.save()
        except Exception as e:
            print e
            self.status = 'error'
            self.save()

trash/forms.py
from django import forms
from models import Trash

POLICY_CHOICES = (('gen_uniq', 'gen_uniq'),
                  ('replace', 'replace'),
                  ('cancel', 'cancel'))


class TaskForm(forms.Form):
    trashes = forms.ChoiceField([(trash.name_trash, trash.trash_dir) for trash in Trash.objects.all()])
    policy = forms.ChoiceField(POLICY_CHOICES)

trash/views.py
from django.views import generic
from django.http import HttpResponseRedirect

from django.db.models.functions import Trunc
import models
from forms import TaskForm
from helper import FileDescrip


import os
import json


class FileManager(generic.ListView):
    template_name = 'file_manager.html'
    context_object_name = 'contents'
    # paginate_by = 25

    def get_previos_path(self):
        return os.path.abspath(os.path.join(self.get_current_path(),
                               os.pardir))

    def get_current_path(self):
        path = self.request.GET.get('path')
        if not path:
            path = '~/'
        path = os.path.expanduser(path)
        return path

    def get_context_data(self, **kwargs):
        context = super(FileManager, self).get_context_data(**kwargs)
        context['previos_dir'] = self.get_previos_path()

        return context

    def get_queryset(self):
        file_list = []
        path = self.get_current_path()
        for name in os.listdir(path):
            file_list.append(FileDescrip(os.path.join(path, name)))
        return file_list


class TrashList(generic.ListView):
    template_name = 'trash_list.html'
    context_object_name = 'trashs'
    model = models.Trash


class TrashView(generic.ListView):
    template_name = 'trash_detail.html'
    model = models.Trash
    context_object_name = 'contents'

    def post(self, request, *args, **kwargs):
        t = models.Trash.objects.filter(trash_dir=self.request.POST.get('path')).first()
        t.clean()
        return HttpResponseRedirect('/trash/')

    def get_current_path(self):
        path = self.request.GET.get('path')
        if not path:
            path = '~/'
        path = os.path.expanduser(path)
        return path

    def get_context_data(self, **kwargs):
        context = super(TrashView, self).get_context_data(**kwargs)
        context['path'] = self.get_current_path()
        return context

    def get_queryset(self):
        file_list = []
        path = self.get_current_path()
        for name in os.listdir(path):
            file_list.append(FileDescrip(os.path.join(path, name)))
        return file_list


class TaskView(generic.ListView):
    template_name = 'task_list.html'
    context_object_name = 'tasks'
    model = models.Task
    paginate_by = 30

    def post(self, request, *args, **kwargs):
        t = models.Trash.objects.filter(name_trash=self.request.POST.get('trashes')).first()
        print self.request.POST
        task = models.Task.objects.create(action=self.request.POST.get('action'),
                                          status='inprogress',
                                          files=json.dumps(self.request.POST.getlist('selected_files')),
                                          trash=t,
                                          regex=self.request.POST.get('regex_str'),
                                          policy=self.request.POST.get('policy'))
        task.execute()

        return HttpResponseRedirect('/task/')

    def get_queryset(self):
        return models.Task.objects.all().order_by('-date')


class TaskCreate(generic.FormView):
    template_name = 'task_creating.html'
    form_class = TaskForm

    def get_context_data(self, **kwargs):
        context = super(TaskCreate, self).get_context_data(**kwargs)
        print self.request.POST
        context['action'] = self.request.POST.get('action')
        context['files'] = self.request.POST.getlist('selected_files')
        return context

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"> -->

    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'main_menu.html' %}
    {% block content %}{% endblock %}
    
    <script src="{% static 'bootstrap/jquery.js' %}"></script>
    <!-- <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> -->
    {% block js %}
    {% endblock %}
</body>
</html> 

templates/file_manager.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-header">
                    <a href="{% url 'trash:filemanager' %}?path={{ previous_dir|urlencode }}">
                        <button type="button" class="btn btn-primary">
                            Back
                        </button>
                    </a>
                </div>
            </div>

     
            <form action="{% url 'trash:task_create'%}" method="POST" class="content-body col-lg-12">
                {% csrf_token %} 
                {% for item in contents %}        
                        {% if item.is_dir %}
                            <div class="file-element">
                                <input type="checkbox" name="selected_files" value="{{ item.get_path }}">
                                <span class="glyphicon glyphicon-folder-close"></span>
                                <a href="{% url 'trash:filemanager' %}?path={{ item.get_path|urlencode }}">
                                    {{ item.get_name }}
                                </a>
                            </div>
                        {% else %}
                            <div class="file-element">
                                <input type="checkbox" name="selected_files" value="{{ item.get_path }}">
                                <span class="glyphicon glyphicon-file" ></span>
                                {{ item.get_name }}
                            </div>
                        {% endif %}     
                {% endfor %}
                <input type="hidden" name="action" value="delete">
                <div class="col-lg-12">
                    <input class="btn btn-danger" type="submit" value="Delete" />
                </div>
            </form>  

        </div>
    </div>


{% endblock %}

templates/main_menu.html
<nav class="navbar navbar-default" style="margin-bottom: 0" navbar-main">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Trash app</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="nav-elem"><a href="{% url 'trash:filemanager' %}">Managers</a></li>
                <li class="nav-elem"><a href="{% url 'trash:trash' %}">Trashes</a></li>
                <li class="nav-elem"><a href="{% url 'trash:task' %}">Tasks</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/task_creating.html
{% extends "base.html"%}

{% block content %}

    <div class="container">
        <form action="{% url 'trash:task' %}" method="POST" class="content-body col-lg-12">
            {% csrf_token %}
            <div class="content-body col-lg-12">
                <table class="table table-bordered">
                    <tr>
                        <th>Selected Files</th>
                        <td>
                            {% for file in files %}
                                <p>
                                    <input type="checkbox" name="selected_files" value="{{ file }}" checked>
                                    {{ file }}
                                </p>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>Actions</th>
                        <td>
                            <p>
                                <input type="hidden" name="action" value="{{ action }}">
                                {{ action }}
                            </p>                       
                        </td>
                    </tr>
                    {% if action == "delete" %}
                    <tr>
                        <th>Regex</th>
                        <td>
                            <input id="regex_str" type="text" name="regex_str">
                            <input id="regex" type="checkbox" name="regex">
                        </td>
                    </tr>
                    {% endif %}
                    {{ form.as_table }}
                </table>
            </div>
            <div class="col-lg-12">
                <input class="btn btn-danger" type="submit" value="Execute" />
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('input[name="regex_str"]').hide();

            $('input[name="regex"]').on('click', function () {
                if ($(this).prop('checked')) {
                    $('input[name="regex_str"]').fadeIn();
                } else {
                    $('input[name="regex_str"]').hide();
                }
            });
        });
    </script>
{% endblock %}

templates/task_list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
	<div class="container">
    	<div class="row">
			<div class="content-body col-lg-12">
				<table class="table table-bordered">
				   	<tr>
				   		<th>Date</th>
				   		<th>Files</th>
   		 				<th>Status</th>
    					<th>Action</th>
    					<th>Trash</th>
   					</tr>
	    		{% for item in tasks %}        
	            		<a href="{% url 'trash:detail_trash' %}?path={{ item.trash_dir|urlencode }}">
	            				<tr>
	            					<td>{{ item.date }}</td>
	            					<td>{{ item.files }}</td>
	            					<td>{{ item.status }}</td>
	           						<td>{{ item.action }}</td>
	           						<td>{{ item.trash }}</td>
	           					</tr>        				
	            		</a>
	    		{% endfor %}
	    		</table>
	    	</div>
	    </div>
    </div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/trash_detail.html
{% extends "base.html"%}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="content-header">
                    <div class="d-inline">
                        <a href="{% url 'trash:trash' %}">
                            <button type="button" class="btn btn-primary">
                                Back
                            </button>
                        </a>
                    </div>
                    <div class="d-inline">
                        <form method="POST">
                            {% csrf_token %} 
                            <input type="hidden" name="path" value="{{ path }}">
                            <input class="btn btn-danger" type="submit" value="Big Red Button" />
                        </form>
                    </div>
                </div>
            </div>
     
            <form action="{% url 'trash:task_create' %}" method="POST" class="content-body col-lg-12">
                {% csrf_token %} 
                {% for item in contents %}        
                        {% if item.is_dir %}
                            <div class="file-element">
                                <input type="checkbox" name="selected_files" value="{{ item.get_path }}">
                                <span class="glyphicon glyphicon-folder-close"></span>
                                {{ item.get_name }}
                            </div>
                        {% else %}
                            <div class="file-element">
                                <input type="checkbox" name="selected_files" value="{{ item.get_path }}">
                                <span class="glyphicon glyphicon-file" ></span>
                                {{ item.get_name }}
                            </div>
                            
                        {% endif %}

                {% endfor %}
                <input type="hidden" name="action" value="restore">
                <div class="col-lg-12">
                    <input class="btn btn-primary" type="submit" value="Restore" />
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/trash_list.html
{% extends "base.html"%}
{% load static %}
{% block content %}
	<div class="container">
    	<div class="row">
			<div class="content-body col-lg-12">
	    		{% for item in trashs %}        
	        		<div class="file-element">

	            		<span class="glyphicon glyphicon-trash"></span>
	            		<a href="{% url 'trash:detail_trash' %}?path={{ item.trash_dir|urlencode }}">
	           				{{ item.trash_dir }}
	            		</a>
	        		</div>    
	    		{% endfor %}
	    	</div>
	    </div>
    </div>
{% endblock %}